#
# Copyright © 2019 VMware, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#
---
- hosts: device-edges
  remote_user: ubuntu
  become: yes
  become_method: sudo
  
  roles:
    - device-edge
